language: r
sudo: false

addons:
  apt:
    packages:
      - libboost-dev

cache:
  packages: true

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
