// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "zarr_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// readAttributesFileHandle
Rcpp::List readAttributesFileHandle(const Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_readAttributesFileHandle(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(readAttributesFileHandle(f));
    return rcpp_result_gen;
END_RCPP
}
// readAttributesGroupHandle
Rcpp::List readAttributesGroupHandle(const Rcpp::XPtr <z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_readAttributesGroupHandle(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr <z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(readAttributesGroupHandle(g));
    return rcpp_result_gen;
END_RCPP
}
// readAttributesDatasetHandle
Rcpp::List readAttributesDatasetHandle(const Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_readAttributesDatasetHandle(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(readAttributesDatasetHandle(d));
    return rcpp_result_gen;
END_RCPP
}
// writeAttributesFileHandle
void writeAttributesFileHandle(const Rcpp::XPtr<z5::filesystem::handle::File> f, const Rcpp::List& l);
RcppExport SEXP _zarr_writeAttributesFileHandle(SEXP fSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type l(lSEXP);
    writeAttributesFileHandle(f, l);
    return R_NilValue;
END_RCPP
}
// writeAttributesGroupHandle
void writeAttributesGroupHandle(const Rcpp::XPtr<z5::filesystem::handle::Group> g, const Rcpp::List& l);
RcppExport SEXP _zarr_writeAttributesGroupHandle(SEXP gSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type l(lSEXP);
    writeAttributesGroupHandle(g, l);
    return R_NilValue;
END_RCPP
}
// writeAttributesDatasetHandle
void writeAttributesDatasetHandle(const Rcpp::XPtr<z5::filesystem::handle::Dataset> d, const Rcpp::List& l);
RcppExport SEXP _zarr_writeAttributesDatasetHandle(SEXP dSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type l(lSEXP);
    writeAttributesDatasetHandle(d, l);
    return R_NilValue;
END_RCPP
}
// removeAttributeFileHandle
void removeAttributeFileHandle(const Rcpp::XPtr<z5::filesystem::handle::File> f, const std::string& key);
RcppExport SEXP _zarr_removeAttributeFileHandle(SEXP fSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    removeAttributeFileHandle(f, key);
    return R_NilValue;
END_RCPP
}
// removeAttributeGroupHandle
void removeAttributeGroupHandle(const Rcpp::XPtr<z5::filesystem::handle::Group> g, const std::string& key);
RcppExport SEXP _zarr_removeAttributeGroupHandle(SEXP gSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    removeAttributeGroupHandle(g, key);
    return R_NilValue;
END_RCPP
}
// removeAttributeDatasetHandle
void removeAttributeDatasetHandle(const Rcpp::XPtr<z5::filesystem::handle::Dataset> d, const std::string& key);
RcppExport SEXP _zarr_removeAttributeDatasetHandle(SEXP dSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    removeAttributeDatasetHandle(d, key);
    return R_NilValue;
END_RCPP
}
// getDatasetHandleFileHandle
Rcpp::XPtr<z5::filesystem::handle::Dataset> getDatasetHandleFileHandle(Rcpp::XPtr<z5::filesystem::handle::File> f, std::string& key);
RcppExport SEXP _zarr_getDatasetHandleFileHandle(SEXP fSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    Rcpp::traits::input_parameter< std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(getDatasetHandleFileHandle(f, key));
    return rcpp_result_gen;
END_RCPP
}
// getDatasetHandleGroupHandle
Rcpp::XPtr<z5::filesystem::handle::Dataset> getDatasetHandleGroupHandle(Rcpp::XPtr<z5::filesystem::handle::Group> g, std::string& key);
RcppExport SEXP _zarr_getDatasetHandleGroupHandle(SEXP gSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    Rcpp::traits::input_parameter< std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(getDatasetHandleGroupHandle(g, key));
    return rcpp_result_gen;
END_RCPP
}
// DatasetHandleIsS3
bool DatasetHandleIsS3(Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_DatasetHandleIsS3(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetHandleIsS3(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetHandleIsGcs
bool DatasetHandleIsGcs(Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_DatasetHandleIsGcs(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetHandleIsGcs(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetHandleExists
bool DatasetHandleExists(Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_DatasetHandleExists(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetHandleExists(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetHandleIsZarr
bool DatasetHandleIsZarr(Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_DatasetHandleIsZarr(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetHandleIsZarr(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetHandlePath
std::string DatasetHandlePath(Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_DatasetHandlePath(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetHandlePath(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetHandleDelete
void DatasetHandleDelete(Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_DatasetHandleDelete(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    DatasetHandleDelete(d);
    return R_NilValue;
END_RCPP
}
// DatasetHandleBucket
std::string DatasetHandleBucket(Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_DatasetHandleBucket(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetHandleBucket(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetHandleNameInBucket
std::string DatasetHandleNameInBucket(Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_DatasetHandleNameInBucket(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetHandleNameInBucket(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetIsZarr
bool DatasetIsZarr(Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetIsZarr(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetIsZarr(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetGetDtype
std::string DatasetGetDtype(Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetGetDtype(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetGetDtype(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetDimension
int DatasetDimension(Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetDimension(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetDimension(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetShape
Rcpp::IntegerVector DatasetShape(Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetShape(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetShape(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetSize
int DatasetSize(const Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetSize(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetSize(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetPath
std::string DatasetPath(const Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetPath(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetPath(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetGetFillValue
SEXP DatasetGetFillValue(const Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetGetFillValue(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetGetFillValue(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetGetCompressor
std::string DatasetGetCompressor(const Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetGetCompressor(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetGetCompressor(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetGetFileMode
std::string DatasetGetFileMode(const Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetGetFileMode(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetGetFileMode(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetGetDefaultChunkSize
int DatasetGetDefaultChunkSize(const Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetGetDefaultChunkSize(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetGetDefaultChunkSize(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetGetDefaultChunkShape
Rcpp::IntegerVector DatasetGetDefaultChunkShape(const Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetGetDefaultChunkShape(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(DatasetGetDefaultChunkShape(d));
    return rcpp_result_gen;
END_RCPP
}
// DatasetRemove
void DatasetRemove(const Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_DatasetRemove(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    DatasetRemove(d);
    return R_NilValue;
END_RCPP
}
// openDatasetDatasetHandle
Rcpp::XPtr<z5::Dataset> openDatasetDatasetHandle(const Rcpp::XPtr<z5::filesystem::handle::Dataset> d);
RcppExport SEXP _zarr_openDatasetDatasetHandle(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(openDatasetDatasetHandle(d));
    return rcpp_result_gen;
END_RCPP
}
// openDatasetFileHandle
Rcpp::XPtr<z5::Dataset> openDatasetFileHandle(const Rcpp::XPtr<z5::filesystem::handle::File> f, const std::string& key);
RcppExport SEXP _zarr_openDatasetFileHandle(SEXP fSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(openDatasetFileHandle(f, key));
    return rcpp_result_gen;
END_RCPP
}
// openDatasetGroupHandle
Rcpp::XPtr<z5::Dataset> openDatasetGroupHandle(const Rcpp::XPtr<z5::filesystem::handle::Group> g, const std::string& key);
RcppExport SEXP _zarr_openDatasetGroupHandle(SEXP gSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(openDatasetGroupHandle(g, key));
    return rcpp_result_gen;
END_RCPP
}
// createDatasetFileHandle
Rcpp::XPtr<z5::Dataset> createDatasetFileHandle(const Rcpp::XPtr<z5::filesystem::handle::File> f, const std::string& key, const std::string& dtype, const Rcpp::IntegerVector& shape, const Rcpp::IntegerVector& chunkShape, const std::string& compressor, const Rcpp::List& compressionOptions, const bool isZarr, const double fillValue);
RcppExport SEXP _zarr_createDatasetFileHandle(SEXP fSEXP, SEXP keySEXP, SEXP dtypeSEXP, SEXP shapeSEXP, SEXP chunkShapeSEXP, SEXP compressorSEXP, SEXP compressionOptionsSEXP, SEXP isZarrSEXP, SEXP fillValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type chunkShape(chunkShapeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type compressor(compressorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type compressionOptions(compressionOptionsSEXP);
    Rcpp::traits::input_parameter< const bool >::type isZarr(isZarrSEXP);
    Rcpp::traits::input_parameter< const double >::type fillValue(fillValueSEXP);
    rcpp_result_gen = Rcpp::wrap(createDatasetFileHandle(f, key, dtype, shape, chunkShape, compressor, compressionOptions, isZarr, fillValue));
    return rcpp_result_gen;
END_RCPP
}
// createDatasetGroupHandle
Rcpp::XPtr<z5::Dataset> createDatasetGroupHandle(const Rcpp::XPtr<z5::filesystem::handle::Group> g, const std::string& key, const std::string& dtype, const Rcpp::IntegerVector& shape, const Rcpp::IntegerVector& chunkShape, const std::string& compressor, const Rcpp::List& compressionOptions, const bool isZarr, const double fillValue);
RcppExport SEXP _zarr_createDatasetGroupHandle(SEXP gSEXP, SEXP keySEXP, SEXP dtypeSEXP, SEXP shapeSEXP, SEXP chunkShapeSEXP, SEXP compressorSEXP, SEXP compressionOptionsSEXP, SEXP isZarrSEXP, SEXP fillValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type chunkShape(chunkShapeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type compressor(compressorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type compressionOptions(compressionOptionsSEXP);
    Rcpp::traits::input_parameter< const bool >::type isZarr(isZarrSEXP);
    Rcpp::traits::input_parameter< const double >::type fillValue(fillValueSEXP);
    rcpp_result_gen = Rcpp::wrap(createDatasetGroupHandle(g, key, dtype, shape, chunkShape, compressor, compressionOptions, isZarr, fillValue));
    return rcpp_result_gen;
END_RCPP
}
// createDatasetDatasetHandle
Rcpp::XPtr<z5::Dataset> createDatasetDatasetHandle(const Rcpp::XPtr<z5::filesystem::handle::Dataset> d, const std::string& dtype, const Rcpp::IntegerVector& shape, const Rcpp::IntegerVector& chunkShape, const std::string& compressor, const Rcpp::List& compressionOptions, const bool isZarr, const double fillValue);
RcppExport SEXP _zarr_createDatasetDatasetHandle(SEXP dSEXP, SEXP dtypeSEXP, SEXP shapeSEXP, SEXP chunkShapeSEXP, SEXP compressorSEXP, SEXP compressionOptionsSEXP, SEXP isZarrSEXP, SEXP fillValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::filesystem::handle::Dataset> >::type d(dSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type chunkShape(chunkShapeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type compressor(compressorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type compressionOptions(compressionOptionsSEXP);
    Rcpp::traits::input_parameter< const bool >::type isZarr(isZarrSEXP);
    Rcpp::traits::input_parameter< const double >::type fillValue(fillValueSEXP);
    rcpp_result_gen = Rcpp::wrap(createDatasetDatasetHandle(d, dtype, shape, chunkShape, compressor, compressionOptions, isZarr, fillValue));
    return rcpp_result_gen;
END_RCPP
}
// getFileHandle
Rcpp::XPtr<z5::filesystem::handle::File> getFileHandle(const std::string& path, const std::string& mode);
RcppExport SEXP _zarr_getFileHandle(SEXP pathSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(getFileHandle(path, mode));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleIsS3
bool FileHandleIsS3(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandleIsS3(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandleIsS3(f));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleIsGcs
bool FileHandleIsGcs(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandleIsGcs(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandleIsGcs(f));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleExists
bool FileHandleExists(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandleExists(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandleExists(f));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleIsZarr
bool FileHandleIsZarr(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandleIsZarr(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandleIsZarr(f));
    return rcpp_result_gen;
END_RCPP
}
// FileHandlePath
std::string FileHandlePath(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandlePath(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandlePath(f));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleDelete
void FileHandleDelete(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandleDelete(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    FileHandleDelete(f);
    return R_NilValue;
END_RCPP
}
// FileHandleKeys
Rcpp::CharacterVector FileHandleKeys(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandleKeys(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandleKeys(f));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleIn
bool FileHandleIn(Rcpp::XPtr<z5::filesystem::handle::File> f, const std::string& key);
RcppExport SEXP _zarr_FileHandleIn(SEXP fSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandleIn(f, key));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleNameInBucket
std::string FileHandleNameInBucket(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandleNameInBucket(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandleNameInBucket(f));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleBucket
std::string FileHandleBucket(Rcpp::XPtr<z5::filesystem::handle::File> f);
RcppExport SEXP _zarr_FileHandleBucket(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(FileHandleBucket(f));
    return rcpp_result_gen;
END_RCPP
}
// FileHandleCreate
void FileHandleCreate(Rcpp::XPtr<z5::filesystem::handle::File> f, const bool isZarr);
RcppExport SEXP _zarr_FileHandleCreate(SEXP fSEXP, SEXP isZarrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    Rcpp::traits::input_parameter< const bool >::type isZarr(isZarrSEXP);
    FileHandleCreate(f, isZarr);
    return R_NilValue;
END_RCPP
}
// getGroupHandleFileHandle
Rcpp::XPtr<z5::filesystem::handle::Group> getGroupHandleFileHandle(Rcpp::XPtr<z5::filesystem::handle::File> f, std::string& key);
RcppExport SEXP _zarr_getGroupHandleFileHandle(SEXP fSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::File> >::type f(fSEXP);
    Rcpp::traits::input_parameter< std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(getGroupHandleFileHandle(f, key));
    return rcpp_result_gen;
END_RCPP
}
// getGroupHandleGroupHandle
Rcpp::XPtr<z5::filesystem::handle::Group> getGroupHandleGroupHandle(Rcpp::XPtr<z5::filesystem::handle::Group> g1, std::string& key);
RcppExport SEXP _zarr_getGroupHandleGroupHandle(SEXP g1SEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(getGroupHandleGroupHandle(g1, key));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleIsS3
bool GroupHandleIsS3(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandleIsS3(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandleIsS3(g));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleIsGcs
bool GroupHandleIsGcs(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandleIsGcs(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandleIsGcs(g));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleExists
bool GroupHandleExists(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandleExists(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandleExists(g));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleIsZarr
bool GroupHandleIsZarr(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandleIsZarr(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandleIsZarr(g));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandlePath
std::string GroupHandlePath(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandlePath(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandlePath(g));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleDelete
void GroupHandleDelete(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandleDelete(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    GroupHandleDelete(g);
    return R_NilValue;
END_RCPP
}
// GroupHandleKeys
Rcpp::CharacterVector GroupHandleKeys(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandleKeys(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandleKeys(g));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleIn
bool GroupHandleIn(Rcpp::XPtr<z5::filesystem::handle::Group> g, const std::string& key);
RcppExport SEXP _zarr_GroupHandleIn(SEXP gSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandleIn(g, key));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleNameInBucket
std::string GroupHandleNameInBucket(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandleNameInBucket(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandleNameInBucket(g));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleBucket
std::string GroupHandleBucket(Rcpp::XPtr<z5::filesystem::handle::Group> g);
RcppExport SEXP _zarr_GroupHandleBucket(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupHandleBucket(g));
    return rcpp_result_gen;
END_RCPP
}
// GroupHandleCreate
void GroupHandleCreate(Rcpp::XPtr<z5::filesystem::handle::Group> g, const bool isZarr);
RcppExport SEXP _zarr_GroupHandleCreate(SEXP gSEXP, SEXP isZarrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::filesystem::handle::Group> >::type g(gSEXP);
    Rcpp::traits::input_parameter< const bool >::type isZarr(isZarrSEXP);
    GroupHandleCreate(g, isZarr);
    return R_NilValue;
END_RCPP
}
// json_to_list
Rcpp::List json_to_list(const std::string s);
RcppExport SEXP _zarr_json_to_list(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(json_to_list(s));
    return rcpp_result_gen;
END_RCPP
}
// list_to_json
std::string list_to_json(const Rcpp::List l);
RcppExport SEXP _zarr_list_to_json(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(list_to_json(l));
    return rcpp_result_gen;
END_RCPP
}
// ListToMetadata
Rcpp::XPtr<z5::DatasetMetadata> ListToMetadata(const Rcpp::List& l);
RcppExport SEXP _zarr_ListToMetadata(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(ListToMetadata(l));
    return rcpp_result_gen;
END_RCPP
}
// MetadataToList
Rcpp::List MetadataToList(Rcpp::XPtr<z5::DatasetMetadata> mptr);
RcppExport SEXP _zarr_MetadataToList(SEXP mptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::DatasetMetadata> >::type mptr(mptrSEXP);
    rcpp_result_gen = Rcpp::wrap(MetadataToList(mptr));
    return rcpp_result_gen;
END_RCPP
}
// createDatasetMetadata
Rcpp::XPtr<z5::DatasetMetadata> createDatasetMetadata(const std::string& dtype, const Rcpp::IntegerVector& shape, const Rcpp::IntegerVector& chunkShape, const bool createAsZarr, const std::string& compressor, const Rcpp::List& compressionOptions, const double fillValue);
RcppExport SEXP _zarr_createDatasetMetadata(SEXP dtypeSEXP, SEXP shapeSEXP, SEXP chunkShapeSEXP, SEXP createAsZarrSEXP, SEXP compressorSEXP, SEXP compressionOptionsSEXP, SEXP fillValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type chunkShape(chunkShapeSEXP);
    Rcpp::traits::input_parameter< const bool >::type createAsZarr(createAsZarrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type compressor(compressorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type compressionOptions(compressionOptionsSEXP);
    Rcpp::traits::input_parameter< const double >::type fillValue(fillValueSEXP);
    rcpp_result_gen = Rcpp::wrap(createDatasetMetadata(dtype, shape, chunkShape, createAsZarr, compressor, compressionOptions, fillValue));
    return rcpp_result_gen;
END_RCPP
}
// getDatasetMetadataDataset
Rcpp::XPtr<z5::DatasetMetadata> getDatasetMetadataDataset(Rcpp::XPtr<z5::Dataset> d);
RcppExport SEXP _zarr_getDatasetMetadataDataset(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<z5::Dataset> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(getDatasetMetadataDataset(d));
    return rcpp_result_gen;
END_RCPP
}
// readSubarray
SEXP readSubarray(const Rcpp::XPtr<z5::Dataset> ds, const Rcpp::IntegerVector& offset, const Rcpp::IntegerVector& shape);
RcppExport SEXP _zarr_readSubarray(SEXP dsSEXP, SEXP offsetSEXP, SEXP shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset> >::type ds(dsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type shape(shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(readSubarray(ds, offset, shape));
    return rcpp_result_gen;
END_RCPP
}
// writeSubarray
void writeSubarray(const Rcpp::XPtr<z5::Dataset>& ds, const SEXP data, const Rcpp::IntegerVector& offset);
RcppExport SEXP _zarr_writeSubarray(SEXP dsSEXP, SEXP dataSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::XPtr<z5::Dataset>& >::type ds(dsSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type offset(offsetSEXP);
    writeSubarray(ds, data, offset);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP run_testthat_tests();

static const R_CallMethodDef CallEntries[] = {
    {"_zarr_readAttributesFileHandle", (DL_FUNC) &_zarr_readAttributesFileHandle, 1},
    {"_zarr_readAttributesGroupHandle", (DL_FUNC) &_zarr_readAttributesGroupHandle, 1},
    {"_zarr_readAttributesDatasetHandle", (DL_FUNC) &_zarr_readAttributesDatasetHandle, 1},
    {"_zarr_writeAttributesFileHandle", (DL_FUNC) &_zarr_writeAttributesFileHandle, 2},
    {"_zarr_writeAttributesGroupHandle", (DL_FUNC) &_zarr_writeAttributesGroupHandle, 2},
    {"_zarr_writeAttributesDatasetHandle", (DL_FUNC) &_zarr_writeAttributesDatasetHandle, 2},
    {"_zarr_removeAttributeFileHandle", (DL_FUNC) &_zarr_removeAttributeFileHandle, 2},
    {"_zarr_removeAttributeGroupHandle", (DL_FUNC) &_zarr_removeAttributeGroupHandle, 2},
    {"_zarr_removeAttributeDatasetHandle", (DL_FUNC) &_zarr_removeAttributeDatasetHandle, 2},
    {"_zarr_getDatasetHandleFileHandle", (DL_FUNC) &_zarr_getDatasetHandleFileHandle, 2},
    {"_zarr_getDatasetHandleGroupHandle", (DL_FUNC) &_zarr_getDatasetHandleGroupHandle, 2},
    {"_zarr_DatasetHandleIsS3", (DL_FUNC) &_zarr_DatasetHandleIsS3, 1},
    {"_zarr_DatasetHandleIsGcs", (DL_FUNC) &_zarr_DatasetHandleIsGcs, 1},
    {"_zarr_DatasetHandleExists", (DL_FUNC) &_zarr_DatasetHandleExists, 1},
    {"_zarr_DatasetHandleIsZarr", (DL_FUNC) &_zarr_DatasetHandleIsZarr, 1},
    {"_zarr_DatasetHandlePath", (DL_FUNC) &_zarr_DatasetHandlePath, 1},
    {"_zarr_DatasetHandleDelete", (DL_FUNC) &_zarr_DatasetHandleDelete, 1},
    {"_zarr_DatasetHandleBucket", (DL_FUNC) &_zarr_DatasetHandleBucket, 1},
    {"_zarr_DatasetHandleNameInBucket", (DL_FUNC) &_zarr_DatasetHandleNameInBucket, 1},
    {"_zarr_DatasetIsZarr", (DL_FUNC) &_zarr_DatasetIsZarr, 1},
    {"_zarr_DatasetGetDtype", (DL_FUNC) &_zarr_DatasetGetDtype, 1},
    {"_zarr_DatasetDimension", (DL_FUNC) &_zarr_DatasetDimension, 1},
    {"_zarr_DatasetShape", (DL_FUNC) &_zarr_DatasetShape, 1},
    {"_zarr_DatasetSize", (DL_FUNC) &_zarr_DatasetSize, 1},
    {"_zarr_DatasetPath", (DL_FUNC) &_zarr_DatasetPath, 1},
    {"_zarr_DatasetGetFillValue", (DL_FUNC) &_zarr_DatasetGetFillValue, 1},
    {"_zarr_DatasetGetCompressor", (DL_FUNC) &_zarr_DatasetGetCompressor, 1},
    {"_zarr_DatasetGetFileMode", (DL_FUNC) &_zarr_DatasetGetFileMode, 1},
    {"_zarr_DatasetGetDefaultChunkSize", (DL_FUNC) &_zarr_DatasetGetDefaultChunkSize, 1},
    {"_zarr_DatasetGetDefaultChunkShape", (DL_FUNC) &_zarr_DatasetGetDefaultChunkShape, 1},
    {"_zarr_DatasetRemove", (DL_FUNC) &_zarr_DatasetRemove, 1},
    {"_zarr_openDatasetDatasetHandle", (DL_FUNC) &_zarr_openDatasetDatasetHandle, 1},
    {"_zarr_openDatasetFileHandle", (DL_FUNC) &_zarr_openDatasetFileHandle, 2},
    {"_zarr_openDatasetGroupHandle", (DL_FUNC) &_zarr_openDatasetGroupHandle, 2},
    {"_zarr_createDatasetFileHandle", (DL_FUNC) &_zarr_createDatasetFileHandle, 9},
    {"_zarr_createDatasetGroupHandle", (DL_FUNC) &_zarr_createDatasetGroupHandle, 9},
    {"_zarr_createDatasetDatasetHandle", (DL_FUNC) &_zarr_createDatasetDatasetHandle, 8},
    {"_zarr_getFileHandle", (DL_FUNC) &_zarr_getFileHandle, 2},
    {"_zarr_FileHandleIsS3", (DL_FUNC) &_zarr_FileHandleIsS3, 1},
    {"_zarr_FileHandleIsGcs", (DL_FUNC) &_zarr_FileHandleIsGcs, 1},
    {"_zarr_FileHandleExists", (DL_FUNC) &_zarr_FileHandleExists, 1},
    {"_zarr_FileHandleIsZarr", (DL_FUNC) &_zarr_FileHandleIsZarr, 1},
    {"_zarr_FileHandlePath", (DL_FUNC) &_zarr_FileHandlePath, 1},
    {"_zarr_FileHandleDelete", (DL_FUNC) &_zarr_FileHandleDelete, 1},
    {"_zarr_FileHandleKeys", (DL_FUNC) &_zarr_FileHandleKeys, 1},
    {"_zarr_FileHandleIn", (DL_FUNC) &_zarr_FileHandleIn, 2},
    {"_zarr_FileHandleNameInBucket", (DL_FUNC) &_zarr_FileHandleNameInBucket, 1},
    {"_zarr_FileHandleBucket", (DL_FUNC) &_zarr_FileHandleBucket, 1},
    {"_zarr_FileHandleCreate", (DL_FUNC) &_zarr_FileHandleCreate, 2},
    {"_zarr_getGroupHandleFileHandle", (DL_FUNC) &_zarr_getGroupHandleFileHandle, 2},
    {"_zarr_getGroupHandleGroupHandle", (DL_FUNC) &_zarr_getGroupHandleGroupHandle, 2},
    {"_zarr_GroupHandleIsS3", (DL_FUNC) &_zarr_GroupHandleIsS3, 1},
    {"_zarr_GroupHandleIsGcs", (DL_FUNC) &_zarr_GroupHandleIsGcs, 1},
    {"_zarr_GroupHandleExists", (DL_FUNC) &_zarr_GroupHandleExists, 1},
    {"_zarr_GroupHandleIsZarr", (DL_FUNC) &_zarr_GroupHandleIsZarr, 1},
    {"_zarr_GroupHandlePath", (DL_FUNC) &_zarr_GroupHandlePath, 1},
    {"_zarr_GroupHandleDelete", (DL_FUNC) &_zarr_GroupHandleDelete, 1},
    {"_zarr_GroupHandleKeys", (DL_FUNC) &_zarr_GroupHandleKeys, 1},
    {"_zarr_GroupHandleIn", (DL_FUNC) &_zarr_GroupHandleIn, 2},
    {"_zarr_GroupHandleNameInBucket", (DL_FUNC) &_zarr_GroupHandleNameInBucket, 1},
    {"_zarr_GroupHandleBucket", (DL_FUNC) &_zarr_GroupHandleBucket, 1},
    {"_zarr_GroupHandleCreate", (DL_FUNC) &_zarr_GroupHandleCreate, 2},
    {"_zarr_json_to_list", (DL_FUNC) &_zarr_json_to_list, 1},
    {"_zarr_list_to_json", (DL_FUNC) &_zarr_list_to_json, 1},
    {"_zarr_ListToMetadata", (DL_FUNC) &_zarr_ListToMetadata, 1},
    {"_zarr_MetadataToList", (DL_FUNC) &_zarr_MetadataToList, 1},
    {"_zarr_createDatasetMetadata", (DL_FUNC) &_zarr_createDatasetMetadata, 7},
    {"_zarr_getDatasetMetadataDataset", (DL_FUNC) &_zarr_getDatasetMetadataDataset, 1},
    {"_zarr_readSubarray", (DL_FUNC) &_zarr_readSubarray, 3},
    {"_zarr_writeSubarray", (DL_FUNC) &_zarr_writeSubarray, 3},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_zarr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
