# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readAttributesGroup <- function(g) {
    .Call(`_zarr_readAttributesGroup`, g)
}

readAttributesDataset <- function(d) {
    .Call(`_zarr_readAttributesDataset`, d)
}

writeAttributesFile <- function(f, l) {
    invisible(.Call(`_zarr_writeAttributesFile`, f, l))
}

writeAttributesGroup <- function(g, l) {
    invisible(.Call(`_zarr_writeAttributesGroup`, g, l))
}

writeAttributesDataset <- function(ds, l) {
    invisible(.Call(`_zarr_writeAttributesDataset`, ds, l))
}

DatasetIsZarr <- function(d) {
    .Call(`_zarr_DatasetIsZarr`, d)
}

DatasetGetDtype <- function(d) {
    .Call(`_zarr_DatasetGetDtype`, d)
}

DatasetDimension <- function(d) {
    .Call(`_zarr_DatasetDimension`, d)
}

DatasetShape <- function(d) {
    .Call(`_zarr_DatasetShape`, d)
}

DatasetSize <- function(d) {
    .Call(`_zarr_DatasetSize`, d)
}

DatasetPath <- function(d) {
    .Call(`_zarr_DatasetPath`, d)
}

DatasetGetFillValue <- function(d) {
    .Call(`_zarr_DatasetGetFillValue`, d)
}

DatasetGetCompressor <- function(d) {
    .Call(`_zarr_DatasetGetCompressor`, d)
}

DatasetGetFileMode <- function(d) {
    .Call(`_zarr_DatasetGetFileMode`, d)
}

DatasetGetDefaultChunkSize <- function(d) {
    .Call(`_zarr_DatasetGetDefaultChunkSize`, d)
}

DatasetGetDefaultChunkShape <- function(d) {
    .Call(`_zarr_DatasetGetDefaultChunkShape`, d)
}

DatasetRemove <- function(d) {
    invisible(.Call(`_zarr_DatasetRemove`, d))
}

openDatasetDataset <- function(d) {
    .Call(`_zarr_openDatasetDataset`, d)
}

openDatasetFile <- function(f, key) {
    .Call(`_zarr_openDatasetFile`, f, key)
}

openDatasetGroup <- function(g, key) {
    .Call(`_zarr_openDatasetGroup`, g, key)
}

createDatasetFile <- function(f, key, dtype, shape, chunkShape, compressor, compressionOptions, fillValue) {
    .Call(`_zarr_createDatasetFile`, f, key, dtype, shape, chunkShape, compressor, compressionOptions, fillValue)
}

createDatasetGroup <- function(g, key, dtype, shape, chunkShape, compressor, compressionOptions, fillValue) {
    .Call(`_zarr_createDatasetGroup`, g, key, dtype, shape, chunkShape, compressor, compressionOptions, fillValue)
}

getFileHandle <- function(path, mode) {
    .Call(`_zarr_getFileHandle`, path, mode)
}

FileHandleIsS3 <- function(f) {
    .Call(`_zarr_FileHandleIsS3`, f)
}

FileHandleIsGcs <- function(f) {
    .Call(`_zarr_FileHandleIsGcs`, f)
}

FileHandleExists <- function(f) {
    .Call(`_zarr_FileHandleExists`, f)
}

FileHandleIsZarr <- function(f) {
    .Call(`_zarr_FileHandleIsZarr`, f)
}

FileHandlePath <- function(f) {
    .Call(`_zarr_FileHandlePath`, f)
}

FileHandleDelete <- function(f) {
    invisible(.Call(`_zarr_FileHandleDelete`, f))
}

FileHandleKeys <- function(f) {
    .Call(`_zarr_FileHandleKeys`, f)
}

FileHandleIn <- function(f, key) {
    .Call(`_zarr_FileHandleIn`, f, key)
}

FileHandleNameInBucket <- function(f) {
    .Call(`_zarr_FileHandleNameInBucket`, f)
}

FileHandleBucket <- function(f) {
    .Call(`_zarr_FileHandleBucket`, f)
}

FileHandleCreate <- function(f) {
    invisible(.Call(`_zarr_FileHandleCreate`, f))
}

getGroupHandleFileHandle <- function(f, key) {
    .Call(`_zarr_getGroupHandleFileHandle`, f, key)
}

getGroupHandleGroupHandle <- function(g1, key) {
    .Call(`_zarr_getGroupHandleGroupHandle`, g1, key)
}

GroupHandleIsS3 <- function(g) {
    .Call(`_zarr_GroupHandleIsS3`, g)
}

GroupHandleIsGcs <- function(g) {
    .Call(`_zarr_GroupHandleIsGcs`, g)
}

GroupHandleExists <- function(g) {
    .Call(`_zarr_GroupHandleExists`, g)
}

GroupHandleIsZarr <- function(g) {
    .Call(`_zarr_GroupHandleIsZarr`, g)
}

GroupHandlePath <- function(g) {
    .Call(`_zarr_GroupHandlePath`, g)
}

GroupHandleDelete <- function(g) {
    invisible(.Call(`_zarr_GroupHandleDelete`, g))
}

GroupHandleKeys <- function(g) {
    .Call(`_zarr_GroupHandleKeys`, g)
}

GroupHandleIn <- function(g, key) {
    .Call(`_zarr_GroupHandleIn`, g, key)
}

GroupHandleNameInBucket <- function(g) {
    .Call(`_zarr_GroupHandleNameInBucket`, g)
}

GroupHandleBucket <- function(g) {
    .Call(`_zarr_GroupHandleBucket`, g)
}

GroupHandleCreate <- function(g) {
    invisible(.Call(`_zarr_GroupHandleCreate`, g))
}

ListToMetadata <- function(l) {
    .Call(`_zarr_ListToMetadata`, l)
}

MetadataToList <- function(mptr) {
    .Call(`_zarr_MetadataToList`, mptr)
}

createDatasetMetadata <- function(dtype, shape, chunkShape, createAsZarr, compressor, compressionOptions, fillValue) {
    .Call(`_zarr_createDatasetMetadata`, dtype, shape, chunkShape, createAsZarr, compressor, compressionOptions, fillValue)
}

readSubarray <- function(ds, offset, shape) {
    .Call(`_zarr_readSubarray`, ds, offset, shape)
}

writeSubarray <- function(ds, data, offset) {
    invisible(.Call(`_zarr_writeSubarray`, ds, data, offset))
}

