# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readAttributesGroup <- function(g) {
    .Call(`_zarr_readAttributesGroup`, g)
}

readAttributesDataset <- function(d) {
    .Call(`_zarr_readAttributesDataset`, d)
}

writeAttributesFile <- function(f, l) {
    invisible(.Call(`_zarr_writeAttributesFile`, f, l))
}

writeAttributesGroup <- function(g, l) {
    invisible(.Call(`_zarr_writeAttributesGroup`, g, l))
}

writeAttributesDataset <- function(ds, l) {
    invisible(.Call(`_zarr_writeAttributesDataset`, ds, l))
}

createFile <- function(f) {
    invisible(.Call(`_zarr_createFile`, f))
}

createGroup <- function(g) {
    invisible(.Call(`_zarr_createGroup`, g))
}

createDataset <- function(d, m) {
    invisible(.Call(`_zarr_createDataset`, d, m))
}

getFileHandle <- function(path, mode) {
    .Call(`_zarr_getFileHandle`, path, mode)
}

FileIsS3 <- function(f) {
    .Call(`_zarr_FileIsS3`, f)
}

FileIsGcs <- function(f) {
    .Call(`_zarr_FileIsGcs`, f)
}

FileExists <- function(f) {
    .Call(`_zarr_FileExists`, f)
}

FileIsZarr <- function(f) {
    .Call(`_zarr_FileIsZarr`, f)
}

FilePath <- function(f) {
    .Call(`_zarr_FilePath`, f)
}

FileDelete <- function(f) {
    invisible(.Call(`_zarr_FileDelete`, f))
}

FileKeys <- function(f) {
    .Call(`_zarr_FileKeys`, f)
}

FileIn <- function(f, key) {
    .Call(`_zarr_FileIn`, f, key)
}

getGroupHandleFile <- function(f, key) {
    .Call(`_zarr_getGroupHandleFile`, f, key)
}

getGroupHandleGroup <- function(g1, key) {
    .Call(`_zarr_getGroupHandleGroup`, g1, key)
}

getDatasetHandleFile <- function(f, key) {
    .Call(`_zarr_getDatasetHandleFile`, f, key)
}

getDatasetHandleGroup <- function(g, key) {
    .Call(`_zarr_getDatasetHandleGroup`, g, key)
}

ListToMetadata <- function(l) {
    .Call(`_zarr_ListToMetadata`, l)
}

MetadataToList <- function(mptr) {
    .Call(`_zarr_MetadataToList`, mptr)
}

createDatasetMetadata <- function(dtype, shape, chunkShape, createAsZarr, compressor, compressionOptions, fillValue) {
    .Call(`_zarr_createDatasetMetadata`, dtype, shape, chunkShape, createAsZarr, compressor, compressionOptions, fillValue)
}

readSubarray <- function(ds, offset, shape) {
    .Call(`_zarr_readSubarray`, ds, offset, shape)
}

writeSubarray <- function(ds, data, offset) {
    invisible(.Call(`_zarr_writeSubarray`, ds, data, offset))
}

