# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        r-version: [3.5, 3.6, 4.0]
        os: [ubuntu-18.04, ubuntu-20.04, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up libraries ubuntu
        if: startsWith(matrix.os, "ubuntu")
        run: sudo apt-get install libblosc-dev
        shell: sh {0}

      - name: Set up libraries macOS
        if: startsWith(matrix.os, "macOS")
        run: echo "macOS"
        shell: sh {0}

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
